name = "SmolyakInterpolation"
uuid = "df4bcd03-a9f0-5e75-adfd-f0a2fc0ae852"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8"
UnPack = "1"
julia = "1.2"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
